programs:
  vad:
    silero:
      command: |
        script/speech_prob "share/silero_vad.onnx"
      adapter: |
        vad_adapter_raw.py --rate 16000 --width 2 --channels 1 --samples-per-chunk 512

  asr:
    google-asr:
      command: |
        script/wav2text --credentials "${data_dir}/credentials.json" --language "pl-PL" "{wav_file}"
      adapter: |
        asr_adapter_wav2text.py

  handle:
    home_assistant:
      command: |
        bin/converse.py --language "${language}" "${url}" "${token_file}"
      adapter: |
        handle_adapter_text.py
      template_args:
        url: "https://{DOMAIN}/api/conversation/process"
        token_file: "${data_dir}/token"
        language: "pl"

  tts:
    google-tts:
      command: |
        script/run --dir "${data_dir}/cache" --language "pl"
      adapter: |
        tts_adapter_text2wav.py


pipelines:
  default:
    vad:
      name: silero
    asr:
      name: google-asr
    handle:
      name: home_assistant
    tts:
      name: google-tts
